export const medicines = [
  {
    id: "madhumeh-win",
    name: "Madhumeh Win",
    category: "Blood Sugar Support",
    pack: "30 Capsules",
    mrp: 750,
    price: 600,
    discount: 20,
    featured: true,
    images: [
      "/medicines/madhumeh-win-1.jpeg",
      "/medicines/madhumeh-win-2.jpeg",
      "/medicines/madhumeh-win-3.jpeg",
    ],
    shortDescription:
      "An Ayurvedic formulation described on the label for blood sugar support.",
    description:
      "Madhumeh Win is an Ayurvedic formulation whose label describes support for maintaining blood sugar levels and general wellness.",
    points: [
      "Supports healthy blood sugar management",
      "Contains Neem, Karela, Jamun and Gudmar",
      "Ayurvedic herbal formulation",
      "Suitable for regular wellness support",
    ],
    ingredients: [
      "Neem Giri Extract",
      "Karela Extract",
      "Jamun",
      "Gudmar",
      "Amla",
      "Arjuna",
      "Giloy",
      "Methi",
      "Chirayata",
    ],
    dosage: "2 capsules twice a day",
  },

  {
    id: "diaba-gen",
    name: "Diaba Gen",
    category: "Blood Sugar Support",
    pack: "30 Capsules",
    mrp: 750,
    price: 600,
    discount: 20,
    featured: true,
    images: [
      "/medicines/diaba-gen-1.jpeg",
      "/medicines/diaba-gen-2.jpeg",
      "/medicines/diaba-gen-3.jpeg",
    ],
    shortDescription:
      "Ayurvedic herbal formulation described on the label for maintaining blood sugar levels.",
    description:
      "Diaba Gen contains a combination of traditional Ayurvedic herbs including Gudmar, Jamun, Vijaysar, Dalchini, Methi and Karela.",
    points: [
      "Supports healthy blood sugar levels",
      "Traditional Ayurvedic herbal ingredients",
      "Contains Gudmar and Jamun",
      "Daily wellness formulation",
    ],
    ingredients: [
      "Gudmar",
      "Gum Acacia",
      "Jamun",
      "Vijaysar",
      "Dalchini",
      "Methi",
      "Daruhaldi",
      "Karela",
      "Guduchi",
      "Pipal",
      "Amaltas",
    ],
    dosage: "1–2 tablets twice a day",
  },

  {
    id: "liv-js",
    name: "Liv-JS",
    category: "Liver & Digestive Wellness",
    pack: "60 Capsules",
    mrp: 630,
    price: 507,
    discount: 18,
    featured: true,
    images: [
      "/medicines/liv-js-1.jpeg",
      "/medicines/liv-js-2.jpeg",
      "/medicines/liv-js-3.jpeg",
    ],
    shortDescription:
      "Ayurvedic herbal formulation for liver and digestive wellness.",
    description:
      "Liv-JS is an Ayurvedic formulation containing Amalaki, Haritaki, Bhumi Amalaki, Kutaki, Guduchi and other traditional herbs.",
    points: [
      "Supports liver wellness",
      "Traditional Ayurvedic formulation",
      "Contains Amalaki and Haritaki",
      "Herbal wellness support",
    ],
    ingredients: [
      "Amalaki",
      "Haritaki",
      "Bhumi Amalaki",
      "Himsra",
      "Kutaki",
      "Mamejak",
      "Guduchi",
      "Kasani",
      "Kalmegh",
      "Arjuna",
      "Bhringraj",
    ],
    dosage: "1–2 capsules twice a day",
  },

  {
    id: "ortho-js",
    name: "Ortho-JS",
    category: "Joint & Mobility",
    pack: "80 Tablets",
    mrp: 585,
    price: 515,
    discount: 12,
    featured: true,
    images: ["/medicines/ortho-js-1.jpeg"],
    shortDescription:
      "Ayurvedic formulation for joint and musculoskeletal wellness.",
    description:
      "Ortho-JS contains traditional ingredients including Guggul, Ashwagandha, Suranjan and Sunthi.",
    points: [
      "Supports joint wellness",
      "Traditional Ayurvedic ingredients",
      "Contains Guggul and Ashwagandha",
      "Supports mobility and musculoskeletal wellness",
    ],
    ingredients: [
      "Guggul",
      "Suranjan",
      "Ashwagandha",
      "Kuchla Purified",
      "Sunthi",
      "Pipal",
      "Gum Acacia",
    ],
    dosage: "1–2 tablets twice a day",
  },

  {
    id: "consto-cure",
    name: "Consto Cure",
    category: "Digestive Wellness",
    pack: "30 Tablets",
    mrp: 370,
    price: 370,
    discount: 0,
    featured: false,
    images: ["/medicines/consto-cure-1.jpeg", "/medicines/consto-cure-2.jpeg"],
    shortDescription:
      "Ayurvedic formulation for digestive and bowel regularity support.",
    description:
      "Consto Cure is a traditional Ayurvedic formulation containing Triphala, Trikatu, Vidanga and other ingredients.",
    points: [
      "Supports digestive wellness",
      "Supports bowel regularity",
      "Traditional Ayurvedic formulation",
      "Contains Triphala and Trikatu",
    ],
    ingredients: [
      "Lavan Bhaskar Churan",
      "Panchlavan",
      "Trikatu",
      "Triphala",
      "Agnimukh Churna",
      "Vidanga",
      "Jeera",
      "Pippali",
    ],
    dosage: "1–2 tablets twice a day",
  },

  {
    id: "immu-boost-js",
    name: "Immu Boost-JS",
    category: "Immunity & Wellness",
    pack: "60 Tablets",
    mrp: 999,
    price: 600,
    discount: 40,
    featured: false,
    images: ["/medicines/immu-boost-js-1.jpeg"],
    shortDescription:
      "Ayurvedic formulation for immunity and antioxidant wellness support.",
    description:
      "Immu Boost-JS contains Gokshur, Amala and Galo/Giloy as described on the product information.",
    points: [
      "Supports immunity",
      "Antioxidant support",
      "Traditional Ayurvedic ingredients",
      "Daily wellness support",
    ],
    ingredients: ["Gokshur", "Amala", "Galo/Giloy", "Gum Acacia"],
    dosage: "1–2 tablets twice a day",
  },

  {
    id: "body-fit",
    name: "Body Fit",
    category: "Weight Management",
    pack: "60 Capsules",
    mrp: 1199,
    price: 719,
    discount: 40,
    featured: true,
    images: [
      "/medicines/body-fit-1.jpeg",
      "/medicines/body-fit-2.jpeg",
      "/medicines/body-fit-3.jpeg",
    ],
    shortDescription:
      "Supplement described on the label as supporting weight management and lean muscle.",
    description:
      "Body Fit is described on its label as a supplement supporting weight management, energy and lean muscle.",
    points: [
      "Supports healthy weight management",
      "Supports energy",
      "Supports lean muscle",
      "Contains Chlorogenic Acid",
    ],
    ingredients: ["Chlorogenic Acid 60%"],
    dosage: "Use according to the product label",
  },

  {
    id: "weight-booster-plus",
    name: "Weight Booster Plus",
    category: "Weight Gain",
    pack: "200 g",
    mrp: 1599,
    price: 969,
    discount: 40,
    featured: false,
    images: [
      "/medicines/weight-booster-plus-1.jpeg",
      "/medicines/weight-booster-plus-2.jpeg",
      "/medicines/weight-booster-plus-3.jpeg",
      "/medicines/weight-booster-plus-4.jpeg",
      "/medicines/weight-booster-plus-5.jpeg",
    ],
    shortDescription:
      "Herbal nutritional powder described on the label for weight gain support.",
    description:
      "Weight Booster Plus is a herbal nutritional powder containing traditional ingredients such as Salam Panja, Safed Musli and Shatavari.",
    points: [
      "Supports weight gain",
      "Herbal nutritional formulation",
      "Supports digestion",
      "Supports energy and nutrition",
    ],
    ingredients: [
      "Salam Panja",
      "Isabgol Chilka",
      "Safed Musli",
      "Tondri Safed",
      "Shatavar Napali",
      "Kahu Jira",
    ],
    dosage: "Use according to the product label",
  },

  {
    id: "skin-gen",
    name: "Skin Gen",
    category: "Skin & Wellness",
    pack: "30 Capsules",
    mrp: 999,
    price: 600,
    discount: 40,
    featured: false,
    images: ["/medicines/skin-gen-1.jpeg", "/medicines/skin-gen-2.jpeg"],
    shortDescription:
      "Ayurvedic formulation for skin, antioxidant and general wellness support.",
    description:
      "Skin Gen contains traditional Ayurvedic ingredients including Neem, Manjistha, Haridra and Amalaki.",
    points: [
      "Supports skin wellness",
      "Antioxidant support",
      "Traditional herbal formulation",
      "Contains Neem and Manjistha",
    ],
    ingredients: [
      "Suddha Gandhak",
      "Neem",
      "Manjistha",
      "Trivrut",
      "Haridra",
      "Amalaki",
      "Kalmegh",
    ],
    dosage: "1–2 capsules twice a day",
  },

  {
    id: "prosto-cure",
    name: "Prosto Cure",
    category: "Men's Wellness",
    pack: "60 Tablets",
    mrp: 1599,
    price: 969,
    discount: 40,
    featured: false,
    images: ["/medicines/prosto-cure-1.JPG", "/medicines/prosto-cure-2.JPG"],
    shortDescription:
      "Ayurvedic men's wellness formulation supporting urinary and prostate wellness.",
    description:
      "Prosto Cure is described on the product information as supporting healthy bladder function and normal urinary flow.",
    points: [
      "Supports urinary wellness",
      "Supports healthy bladder function",
      "Traditional Ayurvedic formulation",
      "Men's wellness support",
    ],
    ingredients: [
      "Chandraprabha Vati",
      "Vridhivadhika Vati",
      "Kanchnar Guggul",
      "Gokshuradi Guggul",
      "Tamra Bhasma",
      "Praval Pishti",
      "Shilajit",
    ],
    dosage: "Use according to the product label",
  },

  {
    id: "femi-plus",
    name: "Femi Plus",
    category: "Women's Wellness",
    pack: "60 Capsules",
    mrp: 1599,
    price: 969,
    discount: 40,
    featured: false,
    images: [
      "/medicines/femi-plus-1.jpeg",
      "/medicines/femi-plus-2.jpeg",
      "/medicines/femi-plus-3.jpeg",
      "/medicines/femi-plus-4.jpeg",
    ],
    shortDescription:
      "Ayurvedic women's wellness formulation supporting vitality and energy.",
    description:
      "Femi Plus is a women's wellness formulation containing Ashwagandha, Gokshura, Shilajit, Ashoka, Lodhra and other ingredients.",
    points: [
      "Supports women's vitality",
      "Supports energy and strength",
      "Traditional Ayurvedic ingredients",
      "Women's wellness formulation",
    ],
    ingredients: [
      "Ashwagandha",
      "Gokshura",
      "Elaichi",
      "Shudha Shilajit",
      "Manjishta",
      "Ashoka",
      "Lodhra",
    ],
    dosage: "1 capsule twice a day before meals",
  },

  {
    id: "shila-drive",
    name: "Shila Drive",
    category: "Men's Wellness",
    pack: "200 g",
    mrp: 2499,
    price: 1500,
    discount: 50,
    featured: false,
    images: ["/medicines/shila-drive-1.jpeg", "/medicines/shila-drive-2.jpeg"],
    shortDescription:
      "Men's wellness formulation described on the label for strength, stamina and vitality.",
    description:
      "Shila Drive contains traditional ingredients including Ashwagandha, Safed Musli, Shatavari and Shilajit.",
    points: [
      "Supports strength and stamina",
      "Men's wellness support",
      "Traditional Ayurvedic ingredients",
      "Contains Ashwagandha and Shilajit",
    ],
    ingredients: [
      "Ashwagandha",
      "Konch Beej",
      "Safed Musli",
      "Shatavari",
      "Pippali",
      "Vidhara",
      "Shilajit",
    ],
    dosage: "1 tablespoon twice a day",
  },

  {
    id: "leucodone",
    name: "Leucodone",
    category: "Women's Wellness",
    pack: "60 Capsules",
    mrp: 1199,
    price: 719,
    discount: 40,
    featured: false,
    images: ["/medicines/leucodone-1.jpeg", "/medicines/leucodone-2.jpeg"],
    shortDescription:
      "Women's wellness formulation described on the product information for vaginal health support.",
    description:
      "Leucodone is a women's wellness formulation described on the product information for supporting vaginal health.",
    points: [
      "Women's wellness support",
      "Supports vaginal health",
      "Traditional formulation",
      "60 capsule pack",
    ],
    ingredients: [],
    dosage: "Use according to the product label",
  },

  {
    id: "breast-grow-plus",
    name: "Breast Grow Plus",
    category: "Women's Wellness",
    pack: "200 g",
    mrp: 1599,
    price: 969,
    discount: 40,
    featured: false,
    images: [
      "/medicines/breast-grow-plus-1.jpeg",
      "/medicines/breast-grow-plus-2.jpeg",
    ],
    shortDescription:
      "Women's wellness powder described on the label for natural breast and hormonal wellness support.",
    description:
      "Breast Grow Plus is a herbal powder containing traditional ingredients including Shatavari, Amla, Ashwagandha and Giloy.",
    points: [
      "Women's wellness formulation",
      "Herbal powder",
      "Contains Shatavari and Ashwagandha",
      "Traditional Ayurvedic ingredients",
    ],
    ingredients: [
      "Giloy",
      "Gambhari",
      "Maju Phal",
      "Methidana",
      "Gokhru",
      "Shatavari",
      "Amla",
      "Ashwagandha",
      "Mulethi",
      "Haldi",
    ],
    dosage: "1 teaspoon twice a day before meals",
  },
];
